# Generated by Django 4.1 on 2022-10-02 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xe', '0001_initial'),
        ('thanhtoan', '0001_initial'),
        ('taixe', '0001_initial'),
        ('hinhthucthue', '0001_initial'),
        ('dieukhoan', '0002_alter_dieukhoan_options'),
        ('nguoithue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hopdong',
            fields=[
                ('id_hopdong', models.CharField(db_column='id_HopDong', max_length=10, primary_key=True, serialize=False)),
                ('ten_hopdong', models.CharField(db_column='Ten_HopDong', max_length=30)),
                ('songaythue', models.IntegerField(db_column='SoNgayThue')),
                ('ngaybatdau', models.DateField(db_column='NgayBatDau')),
                ('ngayketthuc', models.DateField(db_column='NgayKetThuc')),
                ('tongtien', models.DecimalField(db_column='TongTien', decimal_places=0, max_digits=10)),
                ('chiphiphatsinh', models.DecimalField(db_column='ChiPhiPhatSinh', decimal_places=0, max_digits=10)),
                ('tienhoahong', models.DecimalField(db_column='TienHoaHong', decimal_places=0, max_digits=10)),
                ('id_dieukhoan', models.ForeignKey(db_column='id_DieuKhoan', on_delete=django.db.models.deletion.PROTECT, to='dieukhoan.dieukhoan')),
                ('id_hinhthucthue', models.ForeignKey(db_column='id_HinhThucThue', on_delete=django.db.models.deletion.PROTECT, to='hinhthucthue.hinhthucthue')),
                ('id_nguoithue', models.ForeignKey(db_column='id_NguoiThue', on_delete=django.db.models.deletion.PROTECT, to='nguoithue.nguoithue')),
                ('id_taixe', models.ForeignKey(db_column='id_TaiXe', on_delete=django.db.models.deletion.PROTECT, to='taixe.taixe')),
                ('id_thanhtoan', models.ForeignKey(db_column='id_ThanhToan', on_delete=django.db.models.deletion.PROTECT, to='thanhtoan.thanhtoan')),
                ('id_xe', models.ForeignKey(db_column='id_Xe', on_delete=django.db.models.deletion.PROTECT, to='xe.xe')),
            ],
            options={
                'db_table': 'hopdong',
                'managed': True,
            },
        ),
    ]
