# Generated by Django 4.1 on 2022-10-30 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopdong', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopdong',
            name='chiphiphatsinh',
        ),
    ]
