# Generated by Django 4.1 on 2022-11-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopdong', '0002_remove_hopdong_chiphiphatsinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopdong',
            name='tinhtrang',
            field=models.IntegerField(db_column='TinhTrang', default=0),
        ),
    ]
