# Generated by Django 4.1 on 2022-11-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopdong', '0003_hopdong_tinhtrang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopdong',
            name='ten_hopdong',
            field=models.CharField(db_column='Ten_HopDong', max_length=70),
        ),
    ]
