# Generated by Django 4.1 on 2022-10-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('danhmucxe', '0001_initial'),
        ('hangxe', '0002_alter_hangxe_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id_model', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_model', models.CharField(max_length=45)),
                ('sochongoi', models.IntegerField()),
                ('dongia', models.DecimalField(decimal_places=0, max_digits=7)),
                ('hinhanh', models.CharField(db_column='HinhAnh', max_length=255)),
                ('id_danhmucxe', models.ForeignKey(db_column='id_DanhMucXe', on_delete=django.db.models.deletion.PROTECT, to='danhmucxe.danhmucxe')),
                ('id_hangxe', models.ForeignKey(db_column='id_HangXe', on_delete=django.db.models.deletion.PROTECT, to='hangxe.hangxe')),
            ],
            options={
                'db_table': 'model',
                'managed': True,
            },
        ),
    ]
