# Generated by Django 4.1 on 2022-10-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_model_hinhanh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='hinhanh',
        ),
    ]
