# Generated by Django 4.1 on 2022-09-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hangxe',
            fields=[
                ('id_hangxe', models.CharField(db_column='id_HangXe', max_length=10, primary_key=True, serialize=False)),
                ('ten_hangxe', models.CharField(db_column='Ten_HangXe', max_length=30)),
            ],
            options={
                'db_table': 'hangxe',
                'managed': False,
            },
        ),
    ]
