# Generated by Django 4.1 on 2022-10-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thanhtoan',
            fields=[
                ('id_thanhtoan', models.CharField(db_column='id_ThanhToan', max_length=10, primary_key=True, serialize=False)),
                ('phuongthucthanhtoan', models.CharField(db_column='PhuongThucThanhToan', max_length=20)),
            ],
            options={
                'db_table': 'thanhtoan',
                'managed': True,
            },
        ),
    ]
