# Generated by Django 4.1 on 2022-09-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Danhmucxe',
            fields=[
                ('id_danhmucxe', models.CharField(db_column='id_DanhMucXe', max_length=10, primary_key=True, serialize=False)),
                ('ten_danhmucxe', models.CharField(db_column='Ten_DanhMucXe', max_length=30)),
            ],
            options={
                'db_table': 'danhmucxe',
                'managed': True,
            },
        ),
    ]
