# Generated by Django 4.1 on 2022-10-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taikhoan',
            fields=[
                ('id_taikhoan', models.CharField(db_column='id_TaiKhoan', max_length=10, primary_key=True, serialize=False)),
                ('ten_taikhoan', models.CharField(db_column='Ten_TaiKhoan', max_length=30)),
                ('matkhau', models.CharField(db_column='MatKhau', max_length=30)),
                ('loai_taikhoan', models.CharField(db_column='Loai_TaiKhoan', max_length=10)),
            ],
            options={
                'db_table': 'taikhoan',
                'managed': True,
            },
        ),
    ]
