# Generated by Django 4.1 on 2022-10-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taikhoan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.CharField(db_column='id_Admin', max_length=10, primary_key=True, serialize=False)),
                ('ten_admin', models.CharField(db_column='Ten_Admin', max_length=40)),
                ('id_taikhoan', models.ForeignKey(db_column='id_TaiKhoan', on_delete=django.db.models.deletion.PROTECT, to='taikhoan.taikhoan')),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
            },
        ),
    ]
