# Generated by Django 4.1 on 2022-10-30 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='id_taikhoan',
        ),
    ]
