# Generated by Django 4.1 on 2022-10-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taixe',
            fields=[
                ('id_taixe', models.CharField(db_column='id_TaiXe', max_length=10, primary_key=True, serialize=False)),
                ('ten_taixe', models.CharField(db_column='Ten_TaiXe', max_length=30)),
                ('diachi', models.CharField(db_column='DiaChi', max_length=60)),
                ('sdt', models.CharField(db_column='SDT', max_length=11)),
            ],
            options={
                'db_table': 'taixe',
                'managed': True,
            },
        ),
    ]
