# Generated by Django 4.1 on 2022-10-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taixe', '0002_taixe_tinhtrang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taixe',
            name='tinhtrang',
            field=models.IntegerField(db_column='TinhTrang', default=1),
        ),
    ]
