# Generated by Django 4.1 on 2022-10-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('id_xe', models.CharField(db_column='id_Xe', max_length=10, primary_key=True, serialize=False)),
                ('nhienlieu', models.CharField(db_column='NhienLieu', max_length=20)),
                ('sacdienthoai', models.TextField(db_column='SacDienThoai')),
                ('hopso', models.CharField(db_column='HopSo', max_length=20)),
                ('dieuhoa', models.CharField(db_column='DieuHoa', max_length=20)),
                ('cameralui', models.TextField(db_column='CameraLui')),
                ('mieuta', models.CharField(db_column='MieuTa', max_length=255)),
                ('trangthai', models.IntegerField(db_column='TrangThai')),
                ('id_model', models.ForeignKey(db_column='id_Model', on_delete=django.db.models.deletion.PROTECT, to='model.model')),
            ],
            options={
                'db_table': 'xe',
                'managed': True,
            },
        ),
    ]
