# Generated by Django 4.1 on 2022-10-25 12:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe', '0002_alter_xe_cameralui_alter_xe_sacdienthoai'),
    ]

    operations = [
        migrations.AddField(
            model_name='xe',
            name='hinhanh',
            field=models.ImageField(db_column='HinhAnh', default='STR', storage=django.core.files.storage.FileSystemStorage(location='/img/car-image'), upload_to=''),
        ),
        migrations.AddField(
            model_name='xe',
            name='ten_xe',
            field=models.CharField(db_column='TenXe', default='CarName', max_length=30),
        ),
    ]
