# Generated by Django 4.1 on 2022-10-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe', '0003_xe_hinhanh_xe_ten_xe'),
    ]

    operations = [
        migrations.AddField(
            model_name='xe',
            name='giatien',
            field=models.DecimalField(db_column='DonGia', decimal_places=0, default=0, max_digits=1),
        ),
    ]
