# Generated by Django 4.1 on 2022-10-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hinhthucthue',
            fields=[
                ('id_hinhthuc', models.CharField(db_column='id_HinhThuc', max_length=10, primary_key=True, serialize=False)),
                ('ten_hinhthuc', models.CharField(db_column='Ten_HinhThuc', max_length=30)),
                ('uudai', models.DecimalField(db_column='UuDai', decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'hinhthucthue',
                'managed': True,
            },
        ),
    ]
