# Generated by Django 4.1 on 2022-10-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hinhthucthue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hinhthucthue',
            name='uudai',
            field=models.FloatField(db_column='UuDai'),
        ),
    ]
