# Generated by Django 4.1 on 2022-10-30 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nguoithue', '0002_alter_nguoithue_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoithue',
            name='id_taikhoan',
        ),
    ]
