# Generated by Django 4.1 on 2022-09-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dieukhoan',
            fields=[
                ('id_dieukhoan', models.CharField(db_column='id_DieuKhoan', max_length=10, primary_key=True, serialize=False)),
                ('dieukhoanchung', models.CharField(db_column='DieuKhoanChung', max_length=255)),
                ('dieukhoanboithuong', models.CharField(db_column='DieuKhoanBoiThuong', max_length=255)),
                ('dieukhoanphatsinh', models.CharField(db_column='DieuKhoanPhatSinh', max_length=255)),
            ],
            options={
                'db_table': 'dieukhoan',
                'managed': False,
            },
        ),
    ]
