# Generated by Django 4.1 on 2022-09-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieukhoan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dieukhoan',
            options={'managed': True},
        ),
    ]
